### PR TITLE
Create tmp files with `.browserify.js` extension

### PR DESCRIPTION
**Pull request by etpinard**
... instead of `.browserify` to avoid "Invalid file type" logs in `karma@3.1.1` from a patch added in karma-runner/karma#3165

Before https://github.com/nikku/karma-browserify/commit/4ef50afa4ae4cf7bbf645a1e1d6a651f49d50738

```
npm test > npm-test.base.txt
grep Invalid npm-test.base.txt

# gives
30 11 2018 15:42:10.544:WARN [middleware:karma]: Invalid file type, defaulting to js. browserify
30 11 2018 15:42:30.195:WARN [middleware:karma]: Invalid file type, defaulting to js. browserify
30 11 2018 15:42:31.145:WARN [middleware:karma]: Invalid file type, defaulting to js. browserify
```

and after

```
npm test > npm-test.txt
grep Invalid npm-test.txt
# blank!
```

[npm-test.base.txt](https://github.com/nikku/karma-browserify/files/2634931/npm-test.base.txt)
[npm-test.txt](https://github.com/nikku/karma-browserify/files/2634933/npm-test.txt)

I could of course add a test for this, if deemed necessary.

### CODE REVIEW

**Comment by etpinard** [comment]
Ah. Looks like `karma@3` [dropped support for Node@4](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#300-2018-08-09).

I should probably revert https://github.com/nikku/karma-browserify/pull/219/commits/aff7a533934bdcfb7cc1a606ab45af8804ea6b89, unless `karma-browserify` is ok with dropping Node@4 support.

**Comment by bendrucker** [comment]
I think it would be ok to drop Node 4 support as part of karma@3 compatibility. It's almost certainly more important to test on karma@latest than continue to support karma@2.

**Comment by bendrucker** [comment]
If anything a "no WARN logs are printed" test could be nice. If that's too tricky no test against this change is ok too.

**Comment by etpinard** [comment]
@bendrucker thanks for taking a look at my PR!

I should be able to add a test at some point next week.

**Comment by bendrucker** [comment]
Cool! Test is far from required and could even be submitted separately. I would be ok merging this now with:

* node@4 removed from Travis
* `peerDependencies.karma` updated
* `engines.node` updated

**Comment by bendrucker** [comment]
Thanks! Published as a major (because of the peer + node version changes).

**Pull request merged**
