### PR TITLE
Don't apply watchify unless autoWatch=true

### LINKED ISSUE #147: Don't wrap browserify in watchify when autoWatch=false
When `autoWatch=false`, [there's a conditional to keep watchify from rebundling](https://github.com/nikku/karma-browserify/blob/d8b8af13ab834bc693788e39debbd4d050843eb8/lib/bro.js#L173). However, `browserify` is still always wrapped in `watchify`, generating a transform that creates watchers for all files passing through, which can be quite expensive, especially considering they serve no purpose.

### PR DESCRIPTION
**Pull request by pmowrer**
A bit crude, but works. Open to suggestions.

Fixes #147

### CODE REVIEW

**Comment by TheSavior** [comment]
We've been having a lot of flakiness issues with our build process and just tracked it down to watchify throughout our CI build. @pmowrer Thank you very much for finding this and providing a PR to fix it. 

@bendrucker @nikku We'd really like to get this merged to master. We've had to manually publish this PR internally to be able to use it and get back to a stable build.

**Comment by pmowrer** [comment]
@TheSavior Glad to hear that it's helpful! The watchers were breaking on our CI builds as well, exceeding the max amount allowed.

**Comment by TheSavior** [comment]
I wonder if there is a way to write a failing test for this PR to solve. Like verifying that watchify isn't wrapping it, or setting the number of allowed file system watchers to 0 before running a specific test and then setting it back, or spying on one of chokidar's methods. Idk, but it would be valuable to keep a regression from being possible.

**Comment by pmowrer** [comment]
Agreed, I was looking for a way to tell whether watchers were created, but had to punt on it. 

Not as good of a regression catcher, but we could test whether the `configure` function receives a browserify bundle or a watchify bundle.

**Comment by akshah123** [comment]
:+1:

**Comment by TheSavior** [comment]
@pmowrer That is decidedly better than not doing that. :P

**Comment by bendrucker** [comment]
Whenever you guys decide on whether/how/how best to test this ping me and I'll get it in

**Comment by TheSavior** [comment]
@pmowrer, any updates? Are you able to add that test?

**Comment by pmowrer** [comment]
@TheSavior Been meaning to get to it... I'll make some time this afternoon

**Comment by pmowrer** [comment]
@TheSavior @bendrucker Added a test to verify that `chokidar.watch` isn't called on single run. Let's get this merged

**Comment by TheSavior** [comment]
@bendrucker Why would `require.resolve` not work? it looks like the npm package `resolve` *is* `require.resolve`

**Comment by bendrucker** [comment]
Not quite, you need to specify a base directory for the lookup. You resolve the path to watchify and then you resolve chokidar from there.

**Comment by pmowrer** [comment]
Thanks for the explanation @bendrucker. Didn't realize there were those kinds of breaking changes with npm@3. Nasty. Updated the PR with your suggestion.

**Comment by bendrucker** [comment]
Well it's a major version bump from v2—there are supposed to be breaking changes ;)

Flat node_modules is super important for Windows people (of which I'm definitely not one) who have path length limits. It also dramatically reduces storage consumption.

In any case, one more correction and we should be good.

**Comment by pmowrer** [comment]
@bendrucker Are we good to go with this?

**Comment by bendrucker** [comment]
I screwed up my feedback on the last round, will merge today with this last change

**Comment by pmowrer** [comment]
Updated

**Comment by bendrucker** [comment]
Published as 4.4

**Comment by nikku** [comment]
Thanks @pmowrer. Great addition.

**Pull request merged**
