### PR TITLE
List browserify as a peer dependency instead of a normal dependency

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
This lets users specify their own browserify version.
This is is a backwards incompatible change and requires `npm version major`.

Also see #158 for a discussion

### CODE REVIEW

**Comment by Joris-van-der-Wel** [comment]
Any update this? Something to clarify or add?

Thanks

**Comment by nikku** [comment]
The reason I did not merge your changes is that I need to play around a bit more with `peerDependencies` and npm@3.

Two remaining issues:

*    People will regularily install karma-browserify, forgetting about the `browserify` dependency (installed it globally or installed incompatible version...).
    We need to indicate that stuff properly via error messages if we give the user full control over the browserify.
*    Watchify is currently still a normal dependency. In order to work properly it should be a peerDependency too, right?

**Comment by Joris-van-der-Wel** [comment]
> Watchify is currently still a normal dependency. In order to work properly it should be a peerDependency too, right?

Looking at the source for watchify I can see that:

* It only executes `require('browserify')` from the bin and test files. karma-browserify invokes watchify using `require('watchify')`, which does not cause watchify to load browserify on its own.
* watchify lists browserify as a `dependency`, which means that if nothing else depends on browserify, the version that watchify specifies will be used (this is only the case in npm 3, however it will pester the user with warnings every time he uses `npm install`). However if our parent (i.e. the user) depends on browserify, that version will be used. 

So it will work properly, however the user might unknowingly start using the browserify version that watchify specifies.

> People will regularily install karma-browserify, forgetting about the browserify dependency (installed it globally or installed incompatible version...). We need to indicate that stuff properly via error messages if we give the user full control over the browserify.

npm will warn the user if peer dependencies are unmet, it will look something like this:
```
karma-browserify@1.2.3
├── UNMET PEER DEPENDENCY browserify@>=10 <=12
```
or:
```
npm WARN EPEERINVALID karma-browserify@4.4.2 requires a peer of karma@>=0.10 but none was installed.
```

It will keep pestering the user about his when he uses certain npm commands (install, update, ls, etc)

**Comment by nikku** [comment]
I'll probably just catch browserify and watchify require errors and report them to the user as errors.

Stuff in the npm log can easily be overlooked by users, especially because unmet peerDependencies are only warnings.

I'll look into the issue this week and hopefully merge it.

**Comment by nikku** [comment]
Pushed changes to the [5-0 branch](https://github.com/nikku/karma-browserify/tree/5-0). Could you check if it works for you?

**Comment by Joris-van-der-Wel** [comment]
Thanks, I took some time to make sure it works properly for me. I hit an unrelated issue which caused required me to find some free time to debug it.

Anyway, this is working great. I can also verify that watchify is doing its thing.

Also, browserify just released version 13, so maybe you could update the version range to include that before merging? (version 13 is working properly for me)

**Comment by Joris-van-der-Wel** [comment]
Ah, the unrelated issue I was hitting was caused by https://github.com/nikku/karma-browserify/commit/1e26c59579b4a3f58957f755a4912d1c02a0d85d#diff-4cd539e8c14d9e235231f6fe41be90eeR310 which is part of that 5-0 branch. I left a comment there

**Comment by nikku** [comment]
Thanks! I will investigate the browserify version bump and cut a release right after. Thanks for contributing :sunny:.

**Comment by nikku** [comment]
...and follow your suggestion regarding `window` :-).

**Comment by nikku** [comment]
Released as v5.0.0.

**Comment by carneiror** [comment]
Moving from dependency to devDependency created me an issue. Consider the following package dependency tree:

```
root
├── mod-z
│   ├── browserify@13.0.0
│   └── karma-browserify@5.0.0
└── mod-a
    └── browserify@12.0.0
```

If I install this with npm@3 the folder tree will look like this:

```
root
├── mod-a
├── mod-z
│   └── browserify@13.0.0
├── karma-browserify@5.0.0
└── browserify@12.0.0
```

So if I try to run the installed `karma-browserify` from the `mod-z` it will run the  `browserify@12.0.0` and not the `browserify@13.0.0`.

This was not an issue with the previous version because browserify was an explicit dependency.

**Comment by nikku** [comment]
You can always require a compatible version of browserify directly (i.e. in `mod-z`):

```
npm install browserify@0.12.x karma-browserify@latest
```

**Comment by carneiror** [comment]
> You can always require a compatible version of browserify directly (i.e. in mod-z):

Exactly what I am doing :wink:  But IMO its kind awkward a package failing just because npm@3 is not deterministic.

**Comment by carneiror** [comment]
> You can always require a compatible version of browserify directly (i.e. in mod-z):

In the example, `browserify@13.0.0` is the correct version. The clash is only happening because NPM uses alphabetic ordering so `mod-a` is installed first and `browserify@12.0.0` is placed on root.

A possible solution is to install the correct version on the root:

`npm install browserify@0.13.x`

**Comment by nikku** [comment]
Anyhow, there is workarounds that handle that situation. :wink:

**Pull request closed without merging**
