### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package browser-unpack from 1.1.1 to 1.2.0

### CODE REVIEW

**Comment by bendrucker** [comment]
1.2.0 is allowed under the previous version

**Comment by EsrefDurna** [comment]
its the first release after 2 years on browser-unpack, it have so many bug fixes,
+ if you don't ask for it, nobody asks and everyone stays with lower version until npm update been called locally,
its not that npm will give you latest version if you have package-lock file or caching,

thank you

**Comment by EsrefDurna** [comment]
try installing it locally and check the version what comes from npm,

**Comment by bendrucker** [comment]
Yeah, no thanks. People who install fresh get the latest, people with existing module trees on disk or a shrinkwrap are free to update as they see fit. Unless there are fixes specifically related to a package where an older version doesn't work at all I don't bump versions like this.

**Comment by EsrefDurna** [comment]
ok your choice

**Pull request closed without merging**
